version: "3.1"
services:
  node:
    image: node:14.15-alpine
    working_dir: /app/app
    volumes:
      - .:/app
    ports:
      - 1000:3000
    tty: true
  nginx:
    image: nginx:1.19.3-alpine
    ports:
      - 80:80
